# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/Airbnb_Open_Data.csv')  # Replace 'path/to/airbnb_dataset.csv' with the actual file path or URL of the dataset

# Display the first few rows of the DataFrame
print(df.head())

# Get the dimensions of the DataFrame (rows, columns)
print(df.shape)

# View the column names
print(df.columns)

# Get summary statistics of numerical columns
print(df.describe())

# Check for missing values
print(df.isnull().sum())



# Example visualizations
# Histogram of price
plt.figure(figsize=(10, 6))
sns.histplot(data=df, x='price')
plt.title('Histogram of Price')
plt.show()

# Scatter plot of price vs. number of reviews
plt.figure(figsize=(10, 6))

# Convert 'room type' column to categorical data type
df['room type'] = df['room type'].astype('category')

# Remove non-numeric characters from 'price' column
df['price'] = df['price'].str.replace('$', '').str.replace(',', '').astype(float)

# Convert 'price' column to numeric data type
#df['price'] = df['price'].astype(float)
sns.scatterplot(data=df, x='number of reviews', y='price')

plt.title('Scatter Plot of Number of Reviews vs. Price')
plt.show()

# Box plot of room type vs. price
plt.figure(figsize=(10, 6))
sns.boxplot(data=df, x='room type', y='price')
plt.title('Box Plot of Room Type vs. Price')
plt.show()

# Correlation matrix
plt.figure(figsize=(10, 8))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Matrix')
plt.show()

